{
 "title": "Cars Dashboard",
 "description": "added variables/",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_company",
    "query": "SELECT DISTINCT car_company FROM cars\nORDER BY car_company"
   },
   {
    "name": "announcement_year",
    "query": "SELECT DISTINCT EXTRACT(YEAR FROM announcement_date) AS announcement_year FROM public.cars\nORDER BY announcement_year "
   }
  ]
 },
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 5, "x": 1, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(price) AS total_price FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}';"
    }
   ]
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS totatl_listed FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}';"
    }
   ]
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(km) AS avg_km FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}';"
    }
   ]
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(price) AS avg_price FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}';"
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 22, "x": 1, "y": 6 },
   "options": { "content": "```json\n{{{json @root}}}\n```" },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Top 10 Listed car_models",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT car_model, COUNT(*) AS total_cars FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}'\nGROUP BY car_model\nORDER BY total_cars DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Total Listed Cars Per Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(announcement_date, 'Mon') AS month, COUNT(*) AS total_cars FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}'\nGROUP BY TO_CHAR(announcement_date, 'Mon'), TO_CHAR(announcement_date, 'MM')\nORDER BY TO_CHAR(announcement_date, 'MM')::INTEGER;"
    }
   ]
  },
  {
   "title": "Average Price per Month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(announcement_date, 'Mon') AS month, AVG(price) AS avg_price FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}'\nGROUP BY TO_CHAR(announcement_date, 'Mon'), TO_CHAR(announcement_date, 'MM')\nORDER BY TO_CHAR(announcement_date, 'MM')::INTEGER;\n"
    }
   ]
  },
  {
   "title": "Locations with most Listings",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT location, COUNT(*) AS total_listed FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}'\nGROUP BY location\nORDER BY total_listed DESC"
    }
   ]
  },
  {
   "title": "Highest and Lowest price for car_models",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT car_model, MAX(price) AS highest_price, MIN(price) AS lowest_price FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}' AND price IS NOT NULL\nGROUP BY car_model\nORDER BY highest_price DESC;"
    }
   ]
  },
  {
   "title": "Transmisisson",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT transmission, COUNT(*) AS total_cars FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}' AND transmission IS NOT NULL\nGROUP BY transmission;\n"
    }
   ]
  },
  {
   "title": "Lowest & Highest Price",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(price) AS highest_price, MIN(price) AS lowest_price FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}';\n"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel, COUNT(*) FROM cars\nWHERE car_company = '${car_company}' AND EXTRACT(YEAR FROM announcement_date) = '${announcement_year}' AND fuel IS NOT NULL\nGROUP BY fuel;"
    }
   ]
  }
 ]
}