
car_company_mapping = {
    "Land-rover": "Land Rover",
    "Mercedes-Benz": "Mercedes",
    "Bmw": "BMW",
    "mini": "Mini",
    "Alfa-romeo": "Alfa Romeo",
    "Ds": "DS",
    "Dfsk": "DFSK",
    "Rolls-royce": "Rolls-Royce",
    "lancia": "Lancia",
    "Aston-martin": "Aston Martin",
    "Gmc": "GMC"
}

car_model_mapping = {
    "Abarth": {
        "595 cabriolet": "595",
        "595_cabriolet": "595",
        "595 competizione 180ch": "595",
        "595 turismo 165ch": "595"
    },
    "Alfa Romeo": {
        "147 gta": "147",
        "GIULIA": "Giulia",
        "Gtv": "GTV"
    },
    "Aston Martin": {
        "Db9": "DB9"
    },
    "Audi": {
        "sq5": "SQ5",
        "Q3 sportback": "Q3",
        "Rs5": "RS5",
        "A5 sportback": "A5",
        "sq8": "SQ8",
        "A4 allroad": "A4",
        "RS-q3": "RSQ3",
        "a4_allroad": "A4",
        "Rs4": "RS4",
        "A1 sportback": "A1",
        "Sq8": "SQ8",
        "q5_sportback": "Q5",
        "q3_sportback": "Q3",
        "etron_s_line": "e-tron S",
        "e-tron_s_sportback": "e-tron S",
        "Q5 sportback": "Q5",
        "Tt": "TT",
        "a1_sportback": "A1",
        "A5 coupe": "A5",
        "a3_sportback": "A3",
        "Rs6": "RS6",
        "Tts": "TTS",
        "Sq5 sportback": "SQ5",
        "A3 sportback": "A3",
        "Rs q8": "RSQ8",
        "Sq5": "SQ5",
        "A3 berline": "A3",
        "Rs3": "RS3",
        "a5_sportback": "A5"
    },
    "Bentley": {
        "Continental Flying Spur": "Continental",
        "Continental gt": "Continental",
        "Continental gtc": "Continental",
        "Continental s": "Continental",
        "Flying spur": "Continental",
        "Corniche coupé": "Continental",
        "Coupe": "Continental"
    },
    "BMW": {
        "1m": "1M",
        "1_m": "1M",
        "serie_1": "1 Series",
        "serie_1_cabriolet": "1 Series",
        "serie_1_coupe": "1 Series",
        "Serie 1": "1 Series",
        "Serie 2": "2 Series",
        "Serie 2 active toure": "2 Series",
        "Serie 2 coupé": "2 Series",
        "Serie 2 gran coupe": "2 Series",
        "serie_2_gran_coupe": "2 Series",
        "ix3": "iX3",
        "x4m": "X4M",
        "serie3_cabriolet": "3 Series",
        "serie_3_cabriolet": "3 Series",
        "serie_3_gt": "3 Series",
        "Serie 3 GT": "3 Series",
        "Serie 3 coupé": "3 Series",
        "Serie 3": "3 Series",
        "Serie 8 gran coupé": "8 Series",
        "Serie 8 gran coupe": "8 Series",
        "Serie 7": "7 Series",
        "Serie 8": "8 Series",
        "Serie 8 cabriolet": "8 Series",
        "Serie 8 coupé": "8 Series",
        "serie_6_gran_coupe": "6 Series",
        "Serie 6 GT": "6 Series",
        "serie_6_coupe": "6 Series",
        "Serie 6": "6 Series",
        "serie_6_cabriolet": "6 Series",
        "x6m": "X6M",
        "ix": "iX",
        "Serie 4 cabriolet": "4 Series",
        "Serie 4": "4 Series",
        "Serie 4 coupé": "4 Series",
        "Serie 4 gran coupe": "4 Series",
        "Serie 4 gran coupé": "4 Series",
        "x5m": "X5M",
        "Serie 5": "5 Series",
        "Serie 5 gt": "5 Series",
        "Serie 5 GT": "5 Series",
        "x3m": "X3M",
        "z4m": "Z4M",
        "Serie 5 M2": "M2"
    },
    "Chevrolet": {
        "aveo_berline": "Aveo",
        "cmp": "CMP",
        "Cr8": "CR8",
        "orlando": "Orlando",
        "trax": "Trax"
    },
    "Chrysler": {
        "300c": "300C",
        "Grand voyager": "Grand Voyager"
    },
    "Citroen": {
        "C3 aircross": "C3",
        "C3 Picasso": "C3",
        "C3 PLURIEL": "C3",
        "C3 picasso": "C3",
        "C3 Aircross": "C3",
        "C3 Cactus": "C3",
        "C5 Aircross": "C5",
        "C5 aircross": "C5",
        "Berlingo vul": "Berlingo",
        "C4 CACTUS": "C4",
        "grand_c4_spacetourer": "C4",
        "c4_spacetourer": "C4",
        "C4 Aircrossm": "C4",
        "GRAND C4 PICASSO": "C4",
        "C4 picasso": "C4",
        "Grand c4 picasso": "C4",
        "C4 cactus": "C4",
        "C4 Picasso": "C4",
        "C4 spacetourer": "C4",
        "2 cv": "2 CV",
        "C-Elysée": "C-ELYSEE",
        "C-elysee": "C-ELYSEE",
        "Xsara picasso": "XSARA",
        "Xsara": "XSARA",
        "c4x": "C4X",
        "C4 x": "C4X",
        "Ax": "AX",
        "Ds": "DS",
        "c5x": "C5X",
        "Zx": "ZX",
        "ami": "AMI",
        "Saxo": "SAXO"
    },
    "Dacia": {
        "sandero_stepway": "Sandero",
        "Sandero stepway": "Sandero",
        "sandero_streetway": "Sandero",
        "Logan mcv": "Logan",
        "Logan Mcv": "Logan",
        "Dokker Van": "Dokker",
        "Dokker van": "Dokker",
        "spring": "Spring"
    },
    "Daihatsu": {
        "Yrv": "YRV"
    },
    "DFSK": {
        "gloryix5": "Glory ix5",
        "K01I": "K01i"
    },
    "DS": {
        "Ds3": "DS 3",
        "DS 3 Crossback": "DS 3",
        "Ds4": "DS 4",
        "ds4_crossback": "DS 4",
        "Ds4 crossback": "DS 4",
        "DS 4S": "DS 4",
        "Ds5": "DS 5",
        "Ds7 crossback": "DS 7",
        "DS 7 Crossback": "DS 7"
    },
    "Ferrari": {
        "458 italia": "458"
    },
    "Fiat": {
        "Tipo hatchback": "TIPO",
        "Tipo": "TIPO",
        "tipo_hatchback": "TIPO",
        "doblo_classic": "Doblo",
        "doblo_panorama": "Doblo",
        "Stilo": "STILO",
        "Freemont": "FREEMONT",
        "500l": "500L",
        "500l_living": "500L",
        "Grande punto": "Punto",
        "punto_classic": "Punto",
        "GRANDE PUNTO": "Punto",
        "fullback": "Fullback",
        "BRAVA": "Brava",
        "FIORINO": "Fiorino",
        "fiorino_cargo": "Fiorino",
        "500c": "500C"
    },
    "Ford": {
        "Focus c-max": "Focus",
        "Focus 4p": "Focus",
        "Focus 5p": "Focus",
        "FOCUS C-MAX": "Focus",
        "fusion_berline": "Fusion",
        "S-max": "S-Max",
        "C max": "C-Max",
        "grand_c_max": "C-Max",
        "B max": "B-Max",
        "ESCORT": "Escort",
        "Tourneo custom": "Tourneo",
        "Tourneo connect": "Tourneo",
        "tourneo_connect": "Tourneo",
        "CONNECT": "Connect",
        "COUGAR": "Cougar",
        "EXPLORER": "Explorer",
        "COURRIER": "Courrier",
        "mustang_cabriolet": "Mustang",
        "Raptor": "raptor"
    },
    "Honda": {
        "Hr-v": "HR-V",
        "Cr-v": "CR-V",
        "civic_coupe": "Civic",
        "civic_berline": "Civic",
        "civic_tourer": "Civic",
        "Cr-x": "CR-X",
        "BOSS": "Accord"
    },
    "Hyundai": {
        "I40": "i 40",
        "I20": "i 20",
        "I10": "i 10",
        "Grand i10": "i 10",
        "Santa fe": "Santa Fe",
        "grand_santa_fe": "Santa Fe",
        "Grand santa fe": "Santa Fe",
        "IX55": "ix 55",
        "Ix55": "ix 55",
        "genesis_coupe": "Genesis",
        "Ix35": "ix 35",
        "Ioniq Hybrid": "Ioniq",
        "I30": "i 30",
        "CRETA": "Creta"
    },
    "Infiniti": {
        "Ex35": "EX35",
        "Fx35": "FX35"
    },
    "Isuzu": {
        "D-max": "D-MAX"
    },
    "Jaguar": {
        "E-PACE": "E-pase",
        "F-PACE": "F-pase",
        "F-Type": "F-type",
        "S-Type": "S-type",
        "Type s": "S-type",
        "Type x": "X-type",
        "X-Type": "X-type",
        "XE": "Xe",
        "XF": "Xf",
        "XJ": "Xj"
    },
    "Jeep": {
        "Grand Cherokee": "Cherokee",
        "Grand cherokee": "Cherokee",
        "CJ5": "Cj5",
        "M151 mutt": "M151 MUTT"
    },
    "Kia": {
        "sonet": "Sonet",
        "CARNIVAL": "Carnival",
        "Sportage hybrid": "Sportage",
        "Sorento hybrid": "Sorento"
    },
    "Land Rover": {
        "Range rover": "Range Rover",
        "Range rover sport": "Range Rover Sport",
        "range_rover_evoque_cabriolet": "Range Rover Evoque",
        "Range rover evoque": "Range Rover Evoque",
        "Range rover evoque convertible": "Range Rover Evoque",
        "Range rover vogue": "Range Rover Vogue",
        "range_rover_vogue": "Range Rover Vogue",
        "range_rover_velar": "Range Rover Velar",
        "Range rover velar": "Range Rover Velar",
        "Discovery sport": "Discovery Sport"
    },
    "Lexus": {
        "Es": "ES",
        "es": "ES",
        "Ls": "LS",
        "lx": "LX",
        "Lx": "LX",
        "nx": "NX",
        "Rx": "RX",
        "Ux": "UX"
    },
    "Mahindra": {
        "kuv_100": "Kuv 100"
    },
    "Mazda": {
        "Cx-5": "Cx5",
        "CX-5": "Cx5",
        "CX7": "Cx7",
        "MX-5": "Mx5",
        "MPV": "Mpv"
    },
    "Mercedes": {
        "Amg gt": "AMG GT",
        "clk_amg_gtr": "AMG GT",
        "Classe e cabriolet": "E Class",
        "Classe E": "E Class",
        "classe_e_cabriolet": "E Class",
        "classe_e_coupe": "E Class",
        "Classe e coupe": "E Class",
        "Classe e": "E Class",
        "Classe SL": "SL Class",
        "CLASSE SLR": "SLR Class",
        "Classe CLK": "CLK Class",
        "Clk": "CLK Class",
        "Classe GLA": "GLA Class",
        "Gla": "GLA Class",
        "Classe C": "C Class",
        "CLASSE C COUPE": "C Class",
        "Classe c coupe": "C Class",
        "classe_c_cabriolet": "C Class",
        "Classe c": "C Class",
        "Classe B": "B Class",
        "Classe b": "B Class",
        "Classe a berline": "A Class",
        "classe_a_berline": "A Class",
        "Classe A": "A Class",
        "Classe a": "A Class",
        "Classe r": "R Class",
        "Classe ml": "ML Class",
        "CLASSE ML": "ML Class",
        "Classe GLE": "GLE Class",
        "classe_gle_coupe": "GLE Class",
        "Gle coupe": "GLE Class",
        "Gle": "GLE Class",
        "glc_coupe": "GLC Class",
        "Glc": "GLC Class",
        "Glc coupe": "GLC Class",
        "Classe GLC": "GLC Class",
        "CLASSE GLC COUPE": "GLC Class",
        "Classe S": "S Class",
        "classe_s_coupe": "S Class",
        "classe_s_cabriolet": "S Class",
        "Classe s": "S Class",
        "CLASSE CLC": "CLC Class",
        "Clc": "CLC Class",
        "Classe CLS": "CLS Class",
        "Cls": "CLS Class",
        "CLASSE R": "R Class",
        "amg_gle": "AMG GLE",
        "amg_gle_coupe": "AMG GLE",
        "Classe GLS": "GLS Class",
        "Classe g": "G Class",
        "Classe GL": "GL Class",
        "Classe v": "V Class",
        "Classe V": "V Class",
        "amg_glc": "AMG GLC",
        "classe_cla_amg": "AMG CLA",
        "Classe CLA": "CLA Class",
        "Cla": "CLA Class",
        "CLASSE GLK": "GLK Class",
        "Glk": "GLK Class",
        "Classe CL": "CL Class",
        "CLASSE SLS": "SLS Class",
        "Classe SLK": "SLK Class",
        "Slk": "SLK Class",
        "Classe M": "M Class",
        "Classe G": "G Class",
        "Amg gts": "AMG GTS"
    },
    "Mini": {
        "cabrio": "Cabrio",
        "CLUBMAN": "Clubman",
        "cooper": "Cooper",
        "country man": "Countrman",
        "mini_coupe": "Mini",
        "one": "One",
        "paceman": "Paceman"
    },
    "Mitsubishi": {
        "canter": "Canter",
        "colt": "Colt",
        "lancer": "Lancer",
        "nativa": "Nativa",
        "outlander": "Outlander",
        "pajero": "Pajero",
        "pajero sport": "Pajero",
        "Pajero sport": "Pajero"
    },
    "Nissan": {
        "primera": "Primera",
        "X trail": "X-Trail",
        "370Z": "370z",
        "pick up": "Pick-up",
        "PATROL": "Patrol",
        "Patrol GR": "Patrol"
    },
    "Opel": {
        "combo_cargo": "Combo",
        "COMBO": "Combo",
        "Combo life": "Combo",
        "combo_life": "Combo",
        "Gt": "GT",
        "adam_rocks": "Adam",
        "ADAM": "Adam",
        "insignia_grand_sport": "Insignia",
        "MOVANO": "Movano",
        "OMEGA": "Omega",
        "ANTARA": "Antara",
        "MOKKA": "Mokka"
    },
    "Peugeot": {
        "207 cc": "207 CC",
        "407 coupe": "407",
        "407 COUPE": "407",
        "406 COUPE": "406",
        "landtrek": "Landtrek",
        "Partner tepee": "Partner",
        "307 cc": "307 CC",
        "206 cc": "206 CC",
        "Rcz": "RCZ"
    },
    "Porsche": {
        "718_boxster": "718",
        "718_cayman": "718",
        "911_cabriolet": "911",
        "911 Carrera": "911",
        "911_targa": "911",
        "918_spyder": "918",
        "boxster_gts": "Boxster",
        "cayenne_coupe": "Cayenne",
        "Cayenne coupe": "Cayenne",
        "Macan turbo": "Macan",
        "panamera_sport_turismo": "Panamera",
        "taycan": "Taycan",
        "taycan_cross_turismo": "Taycan"
    },
    "Renault": {
        "Megane sedan": "Megane",
        "Megane Cabriolet": "Megane",
        "Megane CC": "Megane",
        "Megane Estate": "Megane",
        "Megane Sedan": "Megane",
        "Megane Coupe": "Megane",
        "Megane estate": "Megane",
        "EXPRESS": "Express",
        "express_van": "Express",
        "Express van": "Express",
        "R19": "19",
        "arkana": "Arkana",
        "Laguna estate": "Laguna",
        "Laguna Coupe": "Laguna",
        "Laguna coupe": "Laguna",
        "Laguna Estate": "Laguna",
        "megane_4": "Megane 4",
        "Samsung sm3": "Samsung SM3",
        "Kangoo Express": "Kangoo",
        "kangoo_ze": "Kangoo",
        "Grand Scenic": "Scenic",
        "Grand Espace": "Espace"
    },
    "Seat": {
        "Altea xl": "Altea",
        "ALTEA XL": "Altea",
        "tarraco": "Tarraco",
        "ALHAMBRA": "Alhambra",
        "LEON ST": "Leon",
        "Leon st": "Leon"
    },
    "Skoda": {
        "RAPID": "Rapid"
    },
    "Smart": {
        "ForTwo": "Fortwo"
    },
    "Ssangyong": {
        "STAVIC": "Stavic"
    },
    "Suzuki": {
        "Grand vitara": "Vitara",
        "Grand Vitara": "Vitara",
        "IGNIS": "Ignis",
        "JIMNY": "Jimny",
        "SAMURAI": "Samurai",
        "Wagon r": "Wagon R",
        "WAGON R": "Wagon R",
        "SPLASH": "Splash",
        "SX4": "Sx-4"
    },
    "Tata": {
        "super_ace": "Super ace"
    },
    "Tesla": {
        "Model x": "Model X",
        "model_y": "Model Y"
    },
    "Toyota": {
        "corolla_cross": "Corolla",
        "corolla_millenium": "Corolla",
        "corolla_sport": "Corolla",
        "corolla_prestige": "Corolla",
        "Corolla verso": "Corolla",
        "Corolla cross": "Corolla",
        "Corolla sport 140": "Corolla",
        "land_cruiser_200": "Land Cruiser",
        "land_cruiser_prado": "Land Cruiser",
        "Land cruiser": "Land Cruiser",
        "VERSO": "Verso",
        "AVENSIS VERSO": "Avensis",
        "fortuner": "Fortuner",
        "Rav-4": "RAV 4",
        "C-hr": "C-HR",
        "yaris_cross": "Yaris",
        "Yaris Verso": "Yaris",
        "Yaris cross": "Yaris",
        "Fj cruiser": "FJ",
        "FJ CRUISER": "FJ",
        "4RUNNER": "4Runner",
        "4runner": "4Runner",
        "SUPRA": "Supra"
    },
    "Volkswagen": {
        "GOLF 5": "Golf 5",
        "GOLF 3": "Golf 3",
        "polo_sedan": "Polo",
        "t-roc": "T-roc",
        "GOLF PLUS": "Golf Plus",
        "Golf plus": "Golf Plus",
        "PASSAT CC": "Passat",
        "Passat cc": "Passat",
        "GOLF 6": "Golf 6",
        "GOLF 8": "Golf 8",
        "GOLF 2": "Golf 2",
        "GOLF 4": "Golf 4",
        "coccinelle_cabriolet": "Coccinelle",
        "COCCINELLE": "Coccinelle",
        "caddy_maxi": "Caddy",
        "caddy_van": "Caddy",
        "e-golf": "Golf",
        "New golf": "Golf",
        "New beetle": "Beetle",
        "NEW BEETLE": "Beetle",
        "Id.3": "id3",
        "EOS": "Eos",
        "CRAFTER": "Crafter",
        "Cc": "CC",
        "TRANSPORTER": "Transporter",
        "SHARAN": "Sharan"
    },
    "Volvo": {
        "V40 Cross Country": "V40",
        "Xc40": "XC40",
        "Xc60": "XC60",
        "Xc70": "XC70",
        "Xc90": "XC90"
    }
}
